# Generated by Django 4.2.7 on 2023-11-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
