version: 2.1
jobs:
  test:
    docker:
      # CircleCIのDocker HubからPythonイメージを指定
      - image: cimg/python:3.9
    environment:
      SECRET_KEY: ${SECRET_KEY}
    steps:
      - checkout
      # 依存関係をインストール
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # データベースをセットアップ（SQLiteを使用している場合は不要）
      - run:
          name: Set up database
          command: |
            . venv/bin/activate
            python manage.py migrate
      # テストを実行
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test

# ワークフローを定義
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
