---
- name: Setup Rails app
  hosts: EC2server
  vars:
    ec2_ip: "{{ lookup('env', 'TF_OUTPUT_EC2_IP') }}"
    rds_endpoint_with_port: "{{ lookup('env', 'TF_OUTPUT_RDS_ENDPOINT') }}"
    rds_password: "{{ lookup('env', 'TF_OUTPUT_RDS_PASSWORD') }}"
  gather_facts: true
  become: true
  tasks:
    - name: Ensure /var/www directory exists
      file:
        path: /var/www
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    - name: Clone repository using git module
      git:
        repo: https://github.com/dende-h/raisetech-live8-sample-app.git
        dest: /var/www/raisetech-live8-sample-app
        force: yes
        clone: yes
        update: yes
      become: false

    # (オプション) Nginxの設定ファイルの配置 (変更がある場合のみ)
    - name: Copy Nginx configuration file
      copy:
        src: /var/www/raisetech-live8-sample-app/raisetech-live8-sample-app.conf
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: restart nginx

    - name: Extract just the RDS endpoint (without port)
      set_fact:
        rds_endpoint: "{{rds_endpoint_with_port.split(':')[0] }}"

    - name: Generate database.yml
      template:
        src: /home/circleci/project/ansible/templates/database.yml.j2
        dest:  /var/www/raisetech-live8-sample-app/config/database.yml
      vars:
        db_host: "{{ rds_endpoint }}"
        db_password: "{{ rds_password }}"

    - name: Generate storage.yml
      template:
        src: /home/circleci/project/ansible/templates/storage.yml.j2
        dest:  /var/www/raisetech-live8-sample-app/config/storage.yml

    - name: Generate application.yml
      template:
        src: /home/circleci/project/ansible/templates/application.yml.j2
        dest:  /var/www/raisetech-live8-sample-app/config/application.yml

    - name: Generate the systemd file
      template:
        src: /home/circleci/project/ansible/templates/systemd.yml.j2
        dest: /etc/systemd/system/unicorn.service

    - name: compile app
      block:

      - name: Bundle install
        shell: bash -lc "cd /var/www/raisetech-live8-sample-app && bundle install"
      
      - name: Generate secret key
        shell: bash -lc "cd /var/www/raisetech-live8-sample-app &&  bundle exec rails secret RAILS_ENV=production"
        register: secret_env

      - name: Replace secret key in application.yml
        lineinfile: #特定の行をファイルに追加または置換する
          path: /var/www/raisetech-live8-sample-app/config/application.yml #記述先を指定
          regexp: <will-be-replaced-key>
          line: "SECRET_KEY_BASE: {{ secret_env.stdout }}" # with_itemsに定義した内容が入る

      - name: Rails app setup
        shell: bash -lc "cd /var/www/raisetech-live8-sample-app && RAILS_ENV=production bin/setup "

      - name: Clear Rails cache
        shell: bash -lc "cd /var/www/raisetech-live8-sample-app &&  RAILS_ENV=production rake tmp:cache:clear"

      - name: Precompile assets
        shell: bash -lc "cd /var/www/raisetech-live8-sample-app &&  RAILS_ENV=production rake assets:precompile"
      become: false
    # nginxの起動
    - name: Start nginx service
      service:
        name: nginx
        state: started
    # Unicornの起動
    - name: Ensure unicorn is started
      service:
        name: unicorn
        state: started
        enabled: yes
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
