- name: Setup Django application environment
  hosts: EC2server
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python, pip, and git
      apt:
        name:
          - python3
          - python3-pip
          - git
          - python3-venv
          - pkg-config
          - default-libmysqlclient-dev
        state: present
        update_cache: yes

    - name: Clone Django project repository
      git:
        repo: 'https://github.com/dende-h/sampleMemoApi.git'
        dest: /sampleMemoApi
        version: dev

    - name: Create a Python virtual environment
      command: python3 -m venv /sampleMemoApi/venv
      args:
        creates: /sampleMemoApi/venv

    - name: Install Python dependencies from requirements.txt
      command: /sampleMemoApi/venv/bin/pip install -r /sampleMemoApi/requirements.txt

    - name: Install Gunicorn in the virtual environment
      command: /sampleMemoApi/venv/bin/pip install gunicorn

    - name: Create Gunicorn systemd service file
      template:
        src: /sampleMemoApi/ansible/templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify:
        - Start Gunicorn service
        - Enable Gunicorn service

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx configuration file
      copy:
        src: /sampleMemoApi/sampleApi.conf
        dest: /etc/nginx/conf.d
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: Start Gunicorn service
      systemd:
        name: gunicorn
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Enable Gunicorn service
      systemd:
        name: gunicorn
        enabled: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted