---
- name: Setup Django application environment
  hosts: EC2server
  become: true
  tasks:
  # python3.12のインストール
    - name: Install dependencies for pyenv and Python build
      yum:
        name:
          - gcc
          - zlib-devel
          - bzip2
          - bzip2-devel
          - readline-devel
          - sqlite
          - sqlite-devel
          - openssl-devel
          - tk-devel
          - libffi-devel
          - make
          - git 
          - openssl-devel  # OpenSSL開発ライブラリの追加
        state: present

      # プロジェクトをCloneする
    - name: Clone Django project repository
      git:
        repo: 'https://github.com/dende-h/sampleMemoApi.git'
        dest: /sampleMemoApi
        version: dev
      # python環境インストール
    - name: Setup Python using pyenv
      block:
        - name: Clone pyenv repository
          git:
            repo: 'https://github.com/pyenv/pyenv.git'
            dest: '/home/ec2-user/.pyenv'
            version: master

        - name: Set environment variables for pyenv
          lineinfile:
            path: /home/ec2-user/.bashrc
            line: "{{ item }}"
            create: yes
          with_items:
            - 'export PYENV_ROOT="$HOME/.pyenv"'
            - 'export PATH="$PYENV_ROOT/bin:$PATH"'
            - 'eval "$(pyenv init --path)"'

        - name: Install Python 3.12 using pyenv
          shell: |
            source /home/ec2-user/.bashrc
            if [[ $(pyenv global) != *3.12* ]]; then
              CONFIGURE_OPTS="-with-openssl=/usr" pyenv install 3.12
              pyenv global 3.12
            fi
          args:
            executable: /bin/bash
            creates: /home/ec2-user/.pyenv/versions/3.12

        - name: Add Python 3.12 to PATH in .bashrc
          lineinfile:
            path: /home/ec2-user/.bashrc
            line: 'export PATH="/home/ec2-user/.pyenv/versions/3.12.0/bin:$PATH"'
            create: yes
      # 依存関係ライブラリのインストール
        - name: Upgrade pip and install required packages
          shell: |
            source /home/ec2-user/.bashrc
            /home/ec2-user/.pyenv/versions/3.12.0/bin/pip install --upgrade pip
            /home/ec2-user/.pyenv/versions/3.12.0/bin/pip install -r /sampleMemoApi/requirements.txt
          args:
            executable: /bin/bash

      # Gunicornのインストール
        - name: Install Gunicorn using pip in pyenv environment
          shell: |
            source /home/ec2-user/.bashrc
            pyenv global 3.12
            pip install gunicorn
          args:
            executable: /bin/bash
      become: false 

    - name: Create Gunicorn systemd service file
      become: yes
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify:
        - Start Gunicorn service
        - Enable Gunicorn service

# Nginxのインストール
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy Nginx configuration file
      copy:
        src: /sampleMemoApi/sampleApi.conf
        dest: /etc/nginx/conf.d
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: Start Gunicorn service
      systemd:
        name: gunicorn
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Enable Gunicorn service
      systemd:
        name: gunicorn
        enabled: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
